project:
  type: website

website:
  title: "Quarto Workshop"
  site-url: https://intelligentsystemslaboratory.github.io/quarto_workshop/
  repo-url: https://github.com/IntelligentSystemsLaboratory/quarto_workshop
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd    
  sidebar:
    style: "docked"
    logo: "./images/nwoap_book_world_library_thumbnail.jpg"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Source Code
        url: https://github.com/IntelligentSystemsLaboratory
      - href: index.qmd
        text: Home
      - href: introduction/index.qmd
        text: Introduction
      - hands_on.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Additional extensions for Sphinx
sphinx:
  config:
    html_js_files:
    - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  extra_extensions:
    - sphinxcontrib.mermaid # Draw diagrams with Mermaid
