project:
  type: website

website:
  title: "Quarto Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd    
  sidebar:
    style: "docked"
    logo: "./images/nwoap_book_world_library_thumbnail.jpg"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Source Code
        url: https://github.com/IntelligentSystemsLaboratory
      - href: index.qmd
        text: Home
      - introduction.qmd
      - hands_on.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



